#! /bin/bash

### BEGIN INIT INFO
# Provides:          zappyServer
# Required-Start:    $local_fs $network $named $time $syslog networking
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       starts and stops the webserver and websocket for controlling raspberry pi
### END INIT INFO

PIDFILE1=/var/run/zappyserver-1.pid
PIDFILE2=/var/run/zappyserver-2.pid

#PATH=/home/pi/zappy:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
pth=/home/pi/zappy

startservers(){
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo "Starting Zappy Server" >&2
  
  pushd $pth
  sudo -H -u pi python3 -m http.server 8000 &
  echo $! > $PIDFILE1
  sudo -H -u pi python3 socketcontrol.py &
  echo $! > $PIDFILE2

  sudo bash runbeacon.sh &

  popd




  
}
stopservers(){
  if [ ! -f "$PIDFILE1" ] || ! kill -0 $(cat "$PIDFILE1"); then
    echo 'Http service not running' >&2
  else
    log_begin_msg "Stopping Zappy Http Server"
    kill -15 $(cat "$PIDFILE1") && rm -f "$PIDFILE1"
  fi

  if [ ! -f "$PIDFILE2" ] || ! kill -0 $(cat "$PIDFILE2"); then
    echo 'Python service not running' >&2
  else
    log_begin_msg "Stopping Zappy Python Service"
    kill -15 $(cat "$PIDFILE2") && rm -f "$PIDFILE2"
  fi
  echo "stopped" >&2

  
}
case "$1" in
  start)
    startservers
    ;;
  stop)
    stopservers
    ;;
  restart)
    log_begin_msg "Restarting Zappy Server"
    stopservers
    startservers
  ;;
  *)
    echo "Usage: /etc/init.d/zappyServer {start|stop|restart}"
    exit 1
    ;;
esac