[package]
name = "zappy"
version = "0.1.0"
authors = ["Violet Boyse-Peacor <mookbot@gmail.com>", "SnowingCinders <SnowingCinders@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buttplug = "0.0.2"
